# Generated by Django 3.2.16 on 2025-08-19 21:00

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(default=recipe.models.Recipe.create_random_string, max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
