# Generated by Django 3.2.16 on 2025-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20250731_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default='Pwpc6l', max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
