# Generated by Django 3.2.16 on 2025-07-31 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipeshortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default='szPQRY', max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
