# Generated by Django 3.2.16 on 2025-08-14 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20250813_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 9, 26, 10, 933083, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default='kH5Pqo', max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
