# Generated by Django 3.2.16 on 2025-08-14 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20250814_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default='C4cdvI', max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
