# Generated by Django 3.2.16 on 2025-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20250814_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default='aMYmYG', max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
