# Generated by Django 3.2.16 on 2025-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_alter_recipeshortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default='tmTdK4', max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
