# Generated by Django 3.2.16 on 2025-08-14 09:31

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_recipeshortlink_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_link',
            field=models.CharField(default=recipe.models.create_random_string, max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
