# Generated by Django 3.2.16 on 2025-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/default_avatar.png', null=True, upload_to='users/', verbose_name='Аватар пользователя'),
        ),
    ]
